"""Regenerate `requirements-train.txt` from `.venv-train` (#T-torch-stack).

Reads the installed distributions of the training venv and emits a
hash-pinned requirements file (`--hash=sha256:` per published artifact,
as `pip-compile --generate-hashes` does) so the environment can be
rebuilt byte-identically with `pip install --require-hashes`.

Hashes come from the PyPI JSON API. Network is the ONLY external
dependency: with `JEV_ALLOW_DOWNLOAD=0` (or no network) the script
refuses to write a half-hashed file and exits 2 — a lock file with
missing hashes is worse than no lock file.

Usage:
    .venv-train/bin/python tools/lock_train_reqs.py
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENV_PY = os.path.join(ROOT, ".venv-train", "bin", "python")
OUT = os.path.join(ROOT, "requirements-train.txt")

# Direct asks; everything else in the freeze is a transitive dependency.
DIRECT = ("torch", "transformers", "tokenizers", "safetensors",
          "huggingface-hub", "numpy", "scipy", "scikit-learn", "joblib",
          "cloudpickle")


def frozen() -> list[tuple[str, str]]:
    out = subprocess.run([VENV_PY, "-m", "pip", "freeze", "--all"],
                         capture_output=True, text=True, check=True).stdout
    pins = []
    for line in out.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "==" not in line:
            continue
        name, version = line.split("==", 1)
        pins.append((name.strip(), version.strip()))
    return sorted(pins, key=lambda p: p[0].lower())


def hashes(name: str, version: str) -> list[str]:
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=60) as resp:
        data = json.load(resp)
    digests = {f["digests"]["sha256"] for f in data.get("urls", [])
               if "sha256" in f.get("digests", {})}
    return sorted(digests)


def main() -> int:
    if os.environ.get("JEV_ALLOW_DOWNLOAD", "1") == "0":
        print("[lock] JEV_ALLOW_DOWNLOAD=0: refusing to write a "
              "partial lock file", file=sys.stderr)
        return 2
    lines = [
        "# Training environment for jev-clone (#T-torch-stack).",
        "# GENERATED by tools/lock_train_reqs.py — do not edit by hand.",
        f"# python {sys.version.split()[0]} · regenerated {date.today()}",
        "#",
        "# Rebuild the venv from scratch:",
        "#   python3.14 -m venv .venv-train",
        "#   .venv-train/bin/python -m pip install --require-hashes \\",
        "#       -r requirements-train.txt",
        "#",
        "# Always run training/eval with .venv-train/bin/python: the system",
        "# python has neither sklearn nor torch.",
        "",
    ]
    for name, version in frozen():
        try:
            digests = hashes(name, version)
        except (urllib.error.URLError, TimeoutError) as exc:
            print(f"[lock] {name}=={version}: {exc}", file=sys.stderr)
            return 2
        if not digests:
            print(f"[lock] {name}=={version}: no sha256 on PyPI",
                  file=sys.stderr)
            return 2
        if name.lower().replace("_", "-") not in DIRECT:
            lines.append("# (transitive)")
        lines.append(f"{name}=={version} \\")
        for i, d in enumerate(digests):
            cont = " \\" if i < len(digests) - 1 else ""
            lines.append(f"    --hash=sha256:{d}{cont}")
        lines.append("")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")
    print(f"[lock] wrote {OUT} ({len(frozen())} pins)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
